Translate to Indonesian
sergeicodes/a11ymyths pull request #62
Opened 2024-10-16 07:16 UTC by franzaurus

Hi, [@sergeicodes](https://github.com/sergeicodes).

Thank you for building this cool project. I’m from Indonesia and I’d like to contribute to the Indonesian translation of your Accessibility Myths website. Your website got me curious about the people with disability in my country. It turns out that based on [this 2017 report](https://www.monash.edu/__data/assets/pdf_file/0003/1107138/Disability-in-Indonesia.pdf), _"there are at least 10 million people with some form of disability. This represents 4.3% of the population, based on the latest census which almost certainly understates its prevalence"._

That’s quite a figure. I just hope this meager contribution can help them navigate the web better.

Again, thank you for initiating this project.

-Frans

2024-10-25 14:25 UTC, sergeicodes requested changes
@franzaurus thanks for translating! Please read comments I added, once they are handled, we can release Bahasa Indonesia language.

2024-10-25 14:25 UTC, sergeicodes commented on id/index.html
> +    <link rel="stylesheet" href="./css/styles.css" />
@franzaurus please update `href` to `/css/styles.css` so styles are displayed properly.

2024-10-25 14:25 UTC, sergeicodes commented on id/index.html
> +           </li>
@franzaurus please add a link to Bahasa Indonesia to all languages (`fr/index.html`, `de/index.html`, etc.) 

<img width="963" alt="image" src="https://github.com/user-attachments/assets/b8cdadf0-23a0-448d-9225-aa2016109cb6">

2024-10-25 14:25 UTC, sergeicodes commented on id/index.html
> +    <link rel="icon" type="image/x-icon" href="./favicon.ico" />
@franzaurus please update `href` to `/favicon.ico` so the icon is displayed properly.

2024-10-25 14:35 UTC, sergeicodes commented on id/index.html
> +        </p>
@franzaurus could you please add some info about you (link to your site, github profile or anything you want) here in the footer like in other translations.

2024-10-25 14:55 UTC, sergeicodes commented
@franzaurus please ignore my comments, I'll do everything myself.

2024-10-25 14:55 UTC, merged

2024-10-29 04:10 UTC, franzaurus commented
> @franzaurus please ignore my comments, I'll do everything myself.

Thank you for releasing the Indonesian translation!